FORMAT: 1A
HOST: http://localhost:3000/api/1.0.0

# Kohlife API
Kohlife API is provide for developer.

<!-- include(include/overview.md) -->
<!-- include(include/authentication.md) -->
<!-- include(include/admin.md) -->
<!-- include(include/member.md) -->
<!-- include(include/partners.md) -->
<!-- include(include/omise.md) -->
<!-- include(include/locations.md) -->
<!-- include(include/transportations.md) -->
<!-- include(include/contracts.md) -->
<!-- include(include/booking.md) -->
<!-- include(include/tickets.md) -->